tippy('#cpp-lang', { content: 'C++', });
tippy('#cs-lang', { content: 'C#', });
tippy('#c-lang', { content: 'C', });
tippy('#python-lang', { content: 'Python', });
tippy('#java-lang', { content: 'Java', });
tippy('#js-lang', { content: 'JavaScript', });
tippy('#rust-lang', { content: 'Rust', });
tippy('#ruby-lang', { content: 'Ruby', });
tippy('#php-lang', { content: 'PHP', });
tippy('#html5-lang', { content: 'HTML5', });
tippy('#css3-lang', { content: 'CSS3', });
tippy('#sql-lang', { content: 'SQL', });
tippy('#haskell-lang', { content: 'Haskell', });
tippy('#unity-lang', { content: 'Unity', });
tippy('#unreal-lang', { content: 'Unreal', });
tippy('#pygame-lang', { content: 'Pygame', });
tippy('#vs-lang', { content: 'Visual Studio', });
tippy('#vscode-lang', { content: 'Visual Studio Code', });
tippy('#git-lang', { content: 'Git', });
tippy('#trello-lang', { content: 'Trello', });
tippy('#jetbrains-lang', { content: 'JetBrains', });
tippy('#xcode-lang', { content: 'Kubernetes', });
tippy('#androidstudio-lang', { content: 'Android Studio', });
tippy('#office-lang', { content: 'Office 365', });
tippy('#g-suite-lang', { content: 'G Suite', });
tippy('#adobe-lang', { content: 'Adobe Creative Cloud', });
tippy('#blender-lang', { content: 'Blender', });
tippy('#unity-lang', { content: 'Unity', });
tippy('#unreal-lang', { content: 'Unreal', });
tippy('#photoshop-lang', { content: 'Photoshop', });
tippy('#illustrator-lang', { content: 'Illustrator', });
tippy('#indesign-lang', { content: 'InDesign', });
tippy('#lightroom-lang', { content: 'Lightroom', });

 
